steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - ingest_from_github
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated
 
logsBucket: 'praveen-logs'
 
